# Generated by Django 4.2.5 on 2023-09-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jwt_token_key',
            field=models.CharField(default='BjR5entWlrgi', max_length=12),
        ),
    ]
