# Generated by Django 4.2.5 on 2023-11-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuserroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserroles',
            name='can_add_new_user',
            field=models.BooleanField(default=False),
        ),
    ]
