# Generated by Django 4.2.5 on 2023-10-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_jwt_token_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jwt_token_key',
        ),
    ]
