# Generated by Django 4.2.5 on 2023-11-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuserroles_can_add_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserroles',
            name='can_add_new_roles',
            field=models.BooleanField(default=False),
        ),
    ]
