# Generated by Django 4.2.5 on 2023-10-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_jwt_token_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forget_password_key',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
