# Generated by Django 4.2.5 on 2023-11-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuserroles_can_add_new_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserroles',
            old_name='can_add_new_roles',
            new_name='can_modify_roles',
        ),
        migrations.RemoveField(
            model_name='customuserroles',
            name='can_add_new_user',
        ),
        migrations.AddField(
            model_name='customuserroles',
            name='can_modify_files',
            field=models.BooleanField(default=False),
        ),
    ]
