# Generated by Django 4.2.5 on 2023-11-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_can_add_new_roles_customuserroles_can_modify_roles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_verification_key',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
