# Generated by Django 4.2.5 on 2023-10-17 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customtokenblacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomTokenBlacklist',
        ),
    ]
