# Generated by Django 4.2.5 on 2023-10-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(unique=True),
        ),
    ]
